worker_processes  1;

events { worker_connections 1024; }

http {
    upstream bookings_upstream {
        server bookings-service:5003;
        # Add more backends here for real balancing
    }

    upstream reviews_upstream {
        server reviews-service:5004;
        # Add more backends here for real balancing
    }

    server {
        listen 8080;

        location /bookings/ {
            proxy_pass http://bookings_upstream/;
        }

        location /reviews/ {
            proxy_pass http://reviews_upstream/;
        }
    }
}
