"""
Rooms Service - Smart Meeting Room System
Author: Maroun El Hajj

This microservice manages:
- meeting rooms (name, capacity, equipment, location)
- room availability (basic flag)
- search / filter API

Authentication:
- expects JWT in Authorization header, generated by Users Service
- only admins and facility managers can create/update/delete rooms
"""

from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from functools import wraps
from typing import Optional
import datetime
import os
import jwt

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv(
    "DATABASE_URL", "sqlite:///rooms.db"
)
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["SECRET_KEY"] = os.getenv(
    "SECRET_KEY", "change-this-secret-key-in-production"
)

db = SQLAlchemy(app)

# ----------------------------------------------------------------------
# Models
# ----------------------------------------------------------------------


class Room(db.Model):
    """DB model for meeting rooms."""

    __tablename__ = "rooms"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False, index=True)
    capacity = db.Column(db.Integer, nullable=False)
    equipment = db.Column(db.String(255), nullable=True)  # comma-separated list
    location = db.Column(db.String(120), nullable=False)
    is_available = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "capacity": self.capacity,
            "equipment": self.equipment,
            "location": self.location,
            "is_available": self.is_available,
            "created_at": self.created_at.isoformat(),
        }


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def sanitize(text: Optional[str]) -> Optional[str]:
    if text is None:
        return None
    bad = ["<", ">", '"', "'", ";", "--", "/*", "*/"]
    out = str(text)
    for b in bad:
        out = out.replace(b, "")
    return out.strip()


def decode_token(auth_header: str):
    if auth_header.startswith("Bearer "):
        token = auth_header[7:]
    else:
        token = auth_header
    return jwt.decode(token, app.config["SECRET_KEY"], algorithms=["HS256"])


def auth_required(fn):
    """All routes (except /health, GET /api/rooms) require a valid token."""

    @wraps(fn)
    def wrapper(*args, **kwargs):
        header = request.headers.get("Authorization")
        if not header:
            return jsonify({"error": "Authorization header missing"}), 401
        try:
            payload = decode_token(header)
        except jwt.ExpiredSignatureError:
            return jsonify({"error": "Token expired"}), 401
        except jwt.InvalidTokenError:
            return jsonify({"error": "Invalid token"}), 401

        return fn(payload, *args, **kwargs)

    return wrapper


def admin_or_facility_required(fn):
    """Decorator: only admins or facility managers."""

    @wraps(fn)
    def wrapper(payload, *args, **kwargs):
        role = payload.get("role")
        if role not in ["admin", "facility_manager"]:
            return jsonify({"error": "Admin or facility manager role required"}), 403
        return fn(payload, *args, **kwargs)

    return wrapper


# ----------------------------------------------------------------------
# Routes
# ----------------------------------------------------------------------


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "healthy", "service": "rooms"}), 200


@app.route("/api/rooms", methods=["POST"])
@auth_required
@admin_or_facility_required
def add_room(payload):
    """
    Create new room.

    JSON body:
    {
        "name": "Room A",
        "capacity": 10,
        "equipment": "projector, whiteboard",
        "location": "Engineering Building - 3rd floor",
        "is_available": true   # optional, defaults True
    }
    """
    data = request.get_json() or {}

    for field in ["name", "capacity", "location"]:
        if not data.get(field):
            return jsonify({"error": f"{field} is required"}), 400

    name = sanitize(data["name"])
    location = sanitize(data["location"])
    equipment = sanitize(data.get("equipment", ""))

    try:
        capacity = int(data["capacity"])
    except (TypeError, ValueError):
        return jsonify({"error": "capacity must be an integer"}), 400

    if capacity <= 0:
        return jsonify({"error": "capacity must be positive"}), 400

    if Room.query.filter_by(name=name).first():
        return jsonify({"error": "Room with this name already exists"}), 409

    room = Room(
        name=name,
        capacity=capacity,
        equipment=equipment,
        location=location,
        is_available=bool(data.get("is_available", True)),
    )

    try:
        db.session.add(room)
        db.session.commit()
        return jsonify({"message": "Room created", "room": room.to_dict()}), 201
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Failed to create room: {exc}"}), 500


@app.route("/api/rooms", methods=["GET"])
def list_rooms():
    """
    List rooms with optional filters using query params:

    - min_capacity (int)
    - location (substring, case-insensitive)
    - equipment (substring, case-insensitive)
    - available (true/false)
    """
    query = Room.query

    min_capacity = request.args.get("min_capacity")
    location = request.args.get("location")
    equipment = request.args.get("equipment")
    available = request.args.get("available")

    if min_capacity is not None:
        try:
            min_cap = int(min_capacity)
            query = query.filter(Room.capacity >= min_cap)
        except ValueError:
            return jsonify({"error": "min_capacity must be an integer"}), 400

    if location:
        query = query.filter(Room.location.ilike(f"%{location}%"))

    if equipment:
        query = query.filter(Room.equipment.ilike(f"%{equipment}%"))

    if available is not None:
        if available.lower() in ["true", "1", "yes"]:
            query = query.filter_by(is_available=True)
        elif available.lower() in ["false", "0", "no"]:
            query = query.filter_by(is_available=False)
        else:
            return jsonify({"error": "available must be true or false"}), 400

    rooms = query.all()
    return jsonify({"rooms": [r.to_dict() for r in rooms], "count": len(rooms)}), 200


@app.route("/api/rooms/<int:room_id>", methods=["GET"])
def get_room(room_id: int):
    room = Room.query.get(room_id)
    if not room:
        return jsonify({"error": "Room not found"}), 404
    return jsonify({"room": room.to_dict()}), 200


@app.route("/api/rooms/<int:room_id>", methods=["PUT"])
@auth_required
@admin_or_facility_required
def update_room(payload, room_id: int):
    room = Room.query.get(room_id)
    if not room:
        return jsonify({"error": "Room not found"}), 404

    data = request.get_json() or {}

    if "name" in data and data["name"]:
        room.name = sanitize(data["name"])

    if "capacity" in data:
        try:
            cap = int(data["capacity"])
        except (TypeError, ValueError):
            return jsonify({"error": "capacity must be an integer"}), 400
        if cap <= 0:
            return jsonify({"error": "capacity must be positive"}), 400
        room.capacity = cap

    if "equipment" in data:
        room.equipment = sanitize(data.get("equipment"))

    if "location" in data and data["location"]:
        room.location = sanitize(data["location"])

    if "is_available" in data:
        room.is_available = bool(data["is_available"])

    try:
        db.session.commit()
        return jsonify({"message": "Room updated", "room": room.to_dict()}), 200
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Update failed: {exc}"}), 500


@app.route("/api/rooms/<int:room_id>", methods=["DELETE"])
@auth_required
@admin_or_facility_required
def delete_room(payload, room_id: int):
    room = Room.query.get(room_id)
    if not room:
        return jsonify({"error": "Room not found"}), 404

    try:
        db.session.delete(room)
        db.session.commit()
        return jsonify({"message": f"Room {room_id} deleted"}), 200
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Delete failed: {exc}"}), 500


if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(host="0.0.0.0", port=5002, debug=True)
