"""
Bookings Service - Smart Meeting Room System
Author: Assistant

Responsibilities:
- Manage meeting room bookings (create/update/cancel)
- Prevent overlapping bookings per room
- Expose availability check and booking history
- Enforce RBAC using JWT tokens generated by Users Service
"""

from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from functools import wraps
from typing import Optional, Tuple, List
import datetime
import logging
import time
import os
import jwt
from logging.handlers import RotatingFileHandler

# ----------------------------------------------------------------------
# App configuration
# ----------------------------------------------------------------------
app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv(
    "DATABASE_URL", "sqlite:///bookings.db"
)
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["SECRET_KEY"] = os.getenv(
    "SECRET_KEY", "change-this-secret-key-in-production"
)

db = SQLAlchemy(app)

# ----------------------------------------------------------------------
# Auditing & rate limiting setup
# ----------------------------------------------------------------------

RATE_LIMIT_REQUESTS = int(os.getenv("RATE_LIMIT_REQUESTS", "60"))  # requests
RATE_LIMIT_WINDOW = int(os.getenv("RATE_LIMIT_WINDOW", "60"))  # seconds
_rate_buckets: dict = {}


def _init_logging():
    """Configure rotating file logging for auditing."""
    os.makedirs("logs", exist_ok=True)
    handler = RotatingFileHandler("logs/bookings.log", maxBytes=500_000, backupCount=3)
    formatter = logging.Formatter(
        "%(asctime)s %(levelname)s %(message)s"
    )
    handler.setFormatter(formatter)
    app.logger.setLevel(logging.INFO)
    app.logger.addHandler(handler)


_init_logging()

# ----------------------------------------------------------------------
# Caching (simple in-memory with TTL)
# ----------------------------------------------------------------------

BOOKING_CACHE_TTL = int(os.getenv("BOOKING_CACHE_TTL", "60"))
_availability_cache: dict = {}
_history_cache: dict = {}


def _cache_get(cache: dict, key):
    entry = cache.get(key)
    if not entry:
        return None
    expires, value = entry
    if time.time() > expires:
        cache.pop(key, None)
        return None
    return value


def _cache_set(cache: dict, key, value):
    cache[key] = (time.time() + BOOKING_CACHE_TTL, value)


def _invalidate_caches_for_room(room_id: int):
    """Clear availability cache entries touching a room."""
    to_delete = [k for k in _availability_cache if k[0] == room_id]
    for k in to_delete:
        _availability_cache.pop(k, None)


def _invalidate_history_for_user(user_id: int):
    _history_cache.pop(user_id, None)

# ----------------------------------------------------------------------
# Models
# ----------------------------------------------------------------------


class Booking(db.Model):
    """SQLAlchemy model representing a room booking."""

    __tablename__ = "bookings"
    __table_args__ = (
        db.Index("ix_booking_room_time", "room_id", "start_time", "end_time"),
    )

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False, index=True)
    username = db.Column(db.String(80), nullable=False)
    room_id = db.Column(db.Integer, nullable=False, index=True)
    room_name = db.Column(db.String(120), nullable=True)
    start_time = db.Column(db.DateTime, nullable=False)
    end_time = db.Column(db.DateTime, nullable=False)
    status = db.Column(db.String(20), default="booked")  # booked | cancelled
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(
        db.DateTime,
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
    )

    def to_dict(self) -> dict:
        """Serialize booking for responses."""
        return {
            "id": self.id,
            "user_id": self.user_id,
            "username": self.username,
            "room_id": self.room_id,
            "room_name": self.room_name,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat(),
            "status": self.status,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def sanitize(text: Optional[str]) -> Optional[str]:
    """Remove obvious SQL/script characters."""
    if text is None:
        return None
    bad = ["<", ">", '"', "'", ";", "--", "/*", "*/"]
    cleaned = str(text)
    for b in bad:
        cleaned = cleaned.replace(b, "")
    return cleaned.strip()


def decode_token(auth_header: str) -> dict:
    """Decode JWT from Authorization header."""
    if auth_header.startswith("Bearer "):
        token = auth_header[7:]
    else:
        token = auth_header
    return jwt.decode(token, app.config["SECRET_KEY"], algorithms=["HS256"])


def _try_decode_for_logging() -> dict:
    """Decode token if present; used for auditing; ignores errors."""
    header = request.headers.get("Authorization")
    if not header:
        return {}
    try:
        return decode_token(header)
    except Exception:  # noqa: BLE001
        return {}


def parse_datetime(value: Optional[str]) -> Tuple[Optional[datetime.datetime], Optional[str]]:
    """Parse ISO datetime string safely."""
    if not value:
        return None, "Datetime value missing"
    try:
        return datetime.datetime.fromisoformat(value), None
    except ValueError:
        return None, "Datetime must be ISO 8601 format (YYYY-MM-DDTHH:MM)"


def auth_required(fn):
    """Require valid JWT on the request."""

    @wraps(fn)
    def wrapper(*args, **kwargs):
        header = request.headers.get("Authorization")
        if not header:
            return jsonify({"error": "Authorization header missing"}), 401
        try:
            payload = decode_token(header)
        except jwt.ExpiredSignatureError:
            return jsonify({"error": "Token expired"}), 401
        except jwt.InvalidTokenError:
            return jsonify({"error": "Invalid token"}), 401
        return fn(payload, *args, **kwargs)

    return wrapper


def _prune_bucket(bucket: List[float], now: float) -> List[float]:
    """Remove timestamps outside the window."""
    return [ts for ts in bucket if now - ts <= RATE_LIMIT_WINDOW]


@app.before_request
def enforce_rate_limit():
    """Simple sliding-window rate limiter per IP + endpoint."""
    if request.endpoint == "health":
        return
    now = time.time()
    key = f"{request.remote_addr}:{request.endpoint}"
    bucket = _rate_buckets.get(key, [])
    bucket = _prune_bucket(bucket, now)
    if len(bucket) >= RATE_LIMIT_REQUESTS:
        return jsonify({"error": "Rate limit exceeded"}), 429
    bucket.append(now)
    _rate_buckets[key] = bucket


@app.after_request
def audit_log(response):
    """Log basic request/response data for auditing."""
    payload = _try_decode_for_logging()
    app.logger.info(
        "user_id=%s role=%s method=%s path=%s status=%s",
        payload.get("user_id"),
        payload.get("role"),
        request.method,
        request.path,
        response.status_code,
    )
    return response


def can_manage_all(role: str) -> bool:
    """Return True if role can manage all bookings."""
    return role in ["admin", "facility_manager", "auditor"]


def _check_conflict(room_id: int, start_time: datetime.datetime, end_time: datetime.datetime, exclude_booking_id: Optional[int] = None) -> List[Booking]:
    """Return bookings that conflict with given time window for a room."""
    query = Booking.query.filter(
        Booking.room_id == room_id,
        Booking.status == "booked",
        Booking.start_time < end_time,
        Booking.end_time > start_time,
    )
    if exclude_booking_id:
        query = query.filter(Booking.id != exclude_booking_id)
    return query.all()


# ----------------------------------------------------------------------
# Routes
# ----------------------------------------------------------------------


@app.route("/health", methods=["GET"])
def health():
    """Lightweight health check."""
    return jsonify({"status": "healthy", "service": "bookings"}), 200


@app.route("/api/bookings", methods=["GET"])
@auth_required
def list_bookings(payload: dict):
    """
    List bookings.

    - Admin / facility_manager / auditor: all bookings
    - Others: only own bookings
    """
    if can_manage_all(payload.get("role", "")):
        bookings = Booking.query.order_by(Booking.start_time.desc()).all()
    else:
        bookings = (
            Booking.query.filter_by(user_id=payload.get("user_id"))
            .order_by(Booking.start_time.desc())
            .all()
        )
    return jsonify({"bookings": [b.to_dict() for b in bookings], "count": len(bookings)}), 200


@app.route("/api/bookings/history/<int:user_id>", methods=["GET"])
@auth_required
def booking_history(payload: dict, user_id: int):
    """
    Retrieve booking history for a user.

    - Admin / facility_manager / auditor: any user
    - Regular users: only their own history
    """
    if not can_manage_all(payload.get("role", "")) and payload.get("user_id") != user_id:
        return jsonify({"error": "Insufficient permissions"}), 403

    cached = _cache_get(_history_cache, user_id)
    if cached is not None:
        return jsonify({"bookings": cached, "count": len(cached)}), 200

    bookings = (
        Booking.query.filter_by(user_id=user_id)
        .order_by(Booking.start_time.desc())
        .all()
    )
    serialized = [b.to_dict() for b in bookings]
    _cache_set(_history_cache, user_id, serialized)
    return jsonify({"bookings": serialized, "count": len(serialized)}), 200


@app.route("/api/bookings/check", methods=["GET"])
def check_availability():
    """
    Check if a room is available for a given time range.

    Query params: room_id, start_time, end_time (ISO format).
    """
    room_id = request.args.get("room_id")
    start_raw = request.args.get("start_time")
    end_raw = request.args.get("end_time")

    if not room_id or not start_raw or not end_raw:
        return jsonify({"error": "room_id, start_time and end_time are required"}), 400

    try:
        room_id_int = int(room_id)
    except ValueError:
        return jsonify({"error": "room_id must be an integer"}), 400

    start_time, err = parse_datetime(start_raw)
    if err:
        return jsonify({"error": err}), 400
    end_time, err = parse_datetime(end_raw)
    if err:
        return jsonify({"error": err}), 400

    if end_time <= start_time:
        return jsonify({"error": "end_time must be after start_time"}), 400

    cache_key = (room_id_int, start_time.isoformat(), end_time.isoformat())
    cached = _cache_get(_availability_cache, cache_key)
    if cached is not None:
        return jsonify(cached), 200

    conflicts = _check_conflict(room_id_int, start_time, end_time)
    result = {
        "room_id": room_id_int,
        "available": len(conflicts) == 0,
        "conflicts": [c.to_dict() for c in conflicts],
    }
    _cache_set(_availability_cache, cache_key, result)
    return (
        jsonify(
            result
        ),
        200,
    )


@app.route("/api/bookings", methods=["POST"])
@auth_required
def create_booking(payload: dict):
    """
    Create a booking.

    JSON body:
    {
        "room_id": 1,
        "room_name": "Conference Room",
        "start_time": "2025-01-01T10:00",
        "end_time": "2025-01-01T11:00",
        "user_id": 5,          # optional, admin/facility only
        "username": "alice"    # optional, admin/facility only
    }
    """
    data = request.get_json() or {}

    for field in ["room_id", "start_time", "end_time"]:
        if not data.get(field):
            return jsonify({"error": f"{field} is required"}), 400

    try:
        room_id = int(data["room_id"])
    except (TypeError, ValueError):
        return jsonify({"error": "room_id must be an integer"}), 400

    start_time, err = parse_datetime(data.get("start_time"))
    if err:
        return jsonify({"error": err}), 400

    end_time, err = parse_datetime(data.get("end_time"))
    if err:
        return jsonify({"error": err}), 400

    if end_time <= start_time:
        return jsonify({"error": "end_time must be after start_time"}), 400

    now = datetime.datetime.utcnow()
    if start_time < now:
        return jsonify({"error": "Bookings must start in the future"}), 400

    target_user_id = payload.get("user_id")
    target_username = payload.get("username", "unknown")
    if can_manage_all(payload.get("role", "")):
        # Admin / facility manager can book on behalf of others
        target_user_id = data.get("user_id", target_user_id)
        target_username = sanitize(data.get("username", target_username)) or target_username

    if not target_user_id:
        return jsonify({"error": "user_id missing in token"}), 400

    conflicts = _check_conflict(room_id, start_time, end_time)
    if conflicts:
        return (
            jsonify(
                {
                    "error": "Room already booked in requested time window",
                    "conflicts": [c.to_dict() for c in conflicts],
                }
            ),
            409,
        )

    booking = Booking(
        user_id=int(target_user_id),
        username=target_username,
        room_id=room_id,
        room_name=sanitize(data.get("room_name")),
        start_time=start_time,
        end_time=end_time,
        status="booked",
    )

    try:
        db.session.add(booking)
        db.session.commit()
        _invalidate_caches_for_room(room_id)
        _invalidate_history_for_user(int(target_user_id))
        return jsonify({"message": "Booking created", "booking": booking.to_dict()}), 201
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Failed to create booking: {exc}"}), 500


@app.route("/api/bookings/<int:booking_id>", methods=["PUT"])
@auth_required
def update_booking(payload: dict, booking_id: int):
    """
    Update a booking time or room.

    - Owners can update their booking
    - Admin / facility_manager can update any booking
    """
    booking = Booking.query.get(booking_id)
    if not booking:
        return jsonify({"error": "Booking not found"}), 404
    old_room_id = booking.room_id

    role = payload.get("role")
    if not can_manage_all(role) and booking.user_id != payload.get("user_id"):
        return jsonify({"error": "Insufficient permissions"}), 403

    data = request.get_json() or {}

    if "room_id" in data:
        try:
            booking.room_id = int(data["room_id"])
        except (TypeError, ValueError):
            return jsonify({"error": "room_id must be an integer"}), 400

    if "room_name" in data:
        booking.room_name = sanitize(data.get("room_name"))

    if "start_time" in data:
        start_time, err = parse_datetime(data.get("start_time"))
        if err:
            return jsonify({"error": err}), 400
        booking.start_time = start_time

    if "end_time" in data:
        end_time, err = parse_datetime(data.get("end_time"))
        if err:
            return jsonify({"error": err}), 400
        booking.end_time = end_time

    if booking.end_time <= booking.start_time:
        return jsonify({"error": "end_time must be after start_time"}), 400

    conflicts = _check_conflict(
        booking.room_id, booking.start_time, booking.end_time, exclude_booking_id=booking.id
    )
    if conflicts:
        return (
            jsonify(
                {
                    "error": "Room already booked in requested time window",
                    "conflicts": [c.to_dict() for c in conflicts],
                }
            ),
            409,
        )

    try:
        db.session.commit()
        _invalidate_caches_for_room(booking.room_id)
        if old_room_id != booking.room_id:
            _invalidate_caches_for_room(old_room_id)
        _invalidate_history_for_user(booking.user_id)
        return jsonify({"message": "Booking updated", "booking": booking.to_dict()}), 200
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Failed to update booking: {exc}"}), 500


@app.route("/api/bookings/<int:booking_id>", methods=["DELETE"])
@auth_required
def cancel_booking(payload: dict, booking_id: int):
    """
    Cancel a booking (soft delete).
    """
    booking = Booking.query.get(booking_id)
    if not booking:
        return jsonify({"error": "Booking not found"}), 404

    role = payload.get("role")
    if not can_manage_all(role) and booking.user_id != payload.get("user_id"):
        return jsonify({"error": "Insufficient permissions"}), 403

    booking.status = "cancelled"
    try:
        db.session.commit()
        _invalidate_caches_for_room(booking.room_id)
        _invalidate_history_for_user(booking.user_id)
        return jsonify({"message": "Booking cancelled", "booking": booking.to_dict()}), 200
    except Exception as exc:  # noqa: BLE001
        db.session.rollback()
        return jsonify({"error": f"Failed to cancel booking: {exc}"}), 500


# ----------------------------------------------------------------------
# Entrypoint
# ----------------------------------------------------------------------
if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(host="0.0.0.0", port=5003, debug=True)
